apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: centrifugo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ws.steady.ops.last-try.org`)
      kind: Rule
      middlewares:
        - name: cors-headers
          namespace: steady-prod
      services:
        - name: centrifugo
          port: 8000
  tls:
    secretName: centrifugo-tls
