apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steady-prod

resources:
  - ../../base
  - centrifugo-secrets-sealed.yaml
  - ingressroute.yaml

patches:
  - path: configmap-patch.yaml
