apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: centrifugo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ws-stage.steady.ops.last-try.org
    secretName: centrifugo-tls
  rules:
  - host: ws-stage.steady.ops.last-try.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: centrifugo
            port:
              number: 8000
