apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-backend
spec:
  template:
    spec:
      containers:
      - name: platform-backend
        env:
        - name: CORS_ORIGINS
          value: "https://app.steady.ops.last-try.org,https://tg.steady.ops.last-try.org"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-prod
              key: token
