apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: platform-backend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.steady.ops.last-try.org`)
      kind: Rule
      services:
        - name: platform-backend
          port: 3000
  tls:
    secretName: platform-backend-tls
