apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-backend
spec:
  template:
    spec:
      containers:
      - name: platform-backend
        env:
        - name: CORS_ORIGINS
          value: "https://app-stage.steady.ops.last-try.org,https://miniapp-stage.steady.ops.last-try.org"
