apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-backend
spec:
  template:
    spec:
      containers:
        - name: platform-backend
          env:
            - name: ALLOW_DEV_AUTH
              value: "true"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-stage
                  key: token
